"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-09-24 23:50:26.248854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_areas_codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('correo', sa.String(length=320), nullable=False),
    sa.Column('correo_normalizado', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), server_default=sa.text("'AUDITOR_INTERNO'"), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("rol IN ('ADMIN', 'AUDITOR_INTERNO', 'AUDITOR_EXTERNO', 'RESPONSABLE_AREA', 'APROBADOR')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_normalizado', name='uq_usuarios_correo_normalizado')
    )
    op.create_index('ix_usuarios_rol', 'usuarios', ['rol'], unique=False)
    op.create_table('auditorias',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('alcance', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=24), server_default=sa.text("'PLANNED'"), nullable=False),
    sa.Column('fecha_inicio_prevista', sa.DATE(), nullable=True),
    sa.Column('fecha_fin_prevista', sa.DATE(), nullable=True),
    sa.Column('iniciada_en', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('completada_en', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('responsable_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('updated_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("estado IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')", name='ck_auditorias_estado'),
    sa.CheckConstraint('completada_en IS NULL OR iniciada_en IS NULL OR completada_en >= iniciada_en', name='ck_auditorias_fechas_reales'),
    sa.CheckConstraint('fecha_fin_prevista IS NULL OR fecha_inicio_prevista IS NULL OR fecha_fin_prevista >= fecha_inicio_prevista', name='ck_auditorias_fechas_previstas'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_auditorias_codigo')
    )
    op.create_index('ix_auditorias_created_by', 'auditorias', ['created_by_id'], unique=False)
    op.create_index('ix_auditorias_estado_inicio', 'auditorias', ['estado', 'fecha_inicio_prevista'], unique=False)
    op.create_index('ix_auditorias_responsable', 'auditorias', ['responsable_id'], unique=False)
    op.create_index('ix_auditorias_updated_by', 'auditorias', ['updated_by_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('titulo', sa.String(length=240), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=24), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('responsable_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('area_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('updated_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('version_vigente_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("estado IN ('DRAFT', 'ACTIVE', 'OBSOLETE', 'ARCHIVED')", name='ck_documentos_estado'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_documentos_codigo')
    )
    op.create_index('ix_documentos_area_id', 'documentos', ['area_id'], unique=False)
    op.create_index('ix_documentos_created_by', 'documentos', ['created_by_id'], unique=False)
    op.create_index('ix_documentos_estado_area', 'documentos', ['estado', 'area_id'], unique=False)
    op.create_index('ix_documentos_responsable', 'documentos', ['responsable_id'], unique=False)
    op.create_index('ix_documentos_version_vigente', 'documentos', ['version_vigente_id'], unique=False)
    op.create_table('eventos_auditoria',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('actor_snapshot', sa.String(length=320), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.String(length=80), nullable=False),
    sa.Column('ocurrido_en', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('correlation_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('datos_anteriores', sa.JSON(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eventos_actor_fecha', 'eventos_auditoria', ['actor_id', 'ocurrido_en'], unique=False)
    op.create_index('ix_eventos_correlation_id', 'eventos_auditoria', ['correlation_id'], unique=False)
    op.create_index('ix_eventos_entidad_fecha', 'eventos_auditoria', ['entidad_tipo', 'entidad_id', 'ocurrido_en'], unique=False)
    op.create_index('ix_eventos_ocurrido_en', 'eventos_auditoria', ['ocurrido_en'], unique=False)
    op.create_table('hallazgos',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('severidad', sa.String(length=16), nullable=False),
    sa.Column('estado', sa.String(length=24), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('responsable_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('detectado_en', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('fecha_limite', sa.DATE(), nullable=True),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('cerrado_por_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('cerrado_en', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('updated_by_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("estado <> 'CLOSED' OR (cerrado_por_id IS NOT NULL AND cerrado_en IS NOT NULL)", name='ck_hallazgos_cierre_completo'),
    sa.CheckConstraint("estado IN ('OPEN', 'IN_PROGRESS', 'PENDING_VERIFICATION', 'CLOSED', 'ACCEPTED_RISK')", name='ck_hallazgos_estado'),
    sa.CheckConstraint("severidad IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_hallazgos_severidad'),
    sa.CheckConstraint('numero >= 1', name='ck_hallazgos_numero_positivo'),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cerrado_por_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auditoria_id', 'numero', name='uq_hallazgos_auditoria_numero')
    )
    op.create_index('ix_hallazgos_auditoria_estado', 'hallazgos', ['auditoria_id', 'estado'], unique=False)
    op.create_index('ix_hallazgos_cerrado_por', 'hallazgos', ['cerrado_por_id'], unique=False)
    op.create_index('ix_hallazgos_created_by', 'hallazgos', ['created_by_id'], unique=False)
    op.create_index('ix_hallazgos_detectado_en', 'hallazgos', ['detectado_en'], unique=False)
    op.create_index('ix_hallazgos_responsable_estado_limite', 'hallazgos', ['responsable_id', 'estado', 'fecha_limite'], unique=False)
    op.create_table('versiones_documento',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('documento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_version', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('tamano_bytes', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sha256', mysql.CHAR(length=64), nullable=False),
    sa.Column('comentario_cambio', sa.Text(), nullable=True),
    sa.Column('subido_por_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('numero_version >= 1', name='ck_versiones_documento_numero_positivo'),
    sa.CheckConstraint('tamano_bytes >= 0', name='ck_versiones_documento_tamano_no_negativo'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'numero_version', name='uq_versiones_documento_numero'),
    sa.UniqueConstraint('storage_key', name='uq_versiones_documento_storage_key')
    )
    op.create_index('ix_versiones_documento_sha256', 'versiones_documento', ['sha256'], unique=False)
    op.create_index('ix_versiones_documento_subido_por', 'versiones_documento', ['subido_por_id'], unique=False)
    op.create_table('documentos_auditoria',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('documento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('version_documento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('proposito', sa.String(length=40), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('estado_revision', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('asociado_por_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("estado_revision IN ('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED')", name='ck_documentos_auditoria_estado_revision'),
    sa.ForeignKeyConstraint(['asociado_por_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_documento_id'], ['versiones_documento.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auditoria_id', 'version_documento_id', name='uq_documentos_auditoria_version')
    )
    op.create_index('ix_documentos_auditoria_asociado_por', 'documentos_auditoria', ['asociado_por_id'], unique=False)
    op.create_index('ix_documentos_auditoria_documento', 'documentos_auditoria', ['documento_id'], unique=False)
    op.create_index('ix_documentos_auditoria_estado', 'documentos_auditoria', ['auditoria_id', 'estado_revision'], unique=False)
    op.create_index('ix_documentos_auditoria_version_doc', 'documentos_auditoria', ['version_documento_id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tipo', sa.String(length=24), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('tamano_bytes', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('sha256', mysql.CHAR(length=64), nullable=True),
    sa.Column('referencia_url', sa.String(length=2048), nullable=True),
    sa.Column('documento_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('version_documento_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('registrada_por_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("tipo <> 'FILE' OR (storage_key IS NOT NULL AND sha256 IS NOT NULL AND tamano_bytes IS NOT NULL)", name='ck_evidencias_archivo_campos_completos'),
    sa.CheckConstraint("tipo <> 'REFERENCE' OR referencia_url IS NOT NULL", name='ck_evidencias_referencia_url'),
    sa.CheckConstraint("tipo IN ('FILE', 'REFERENCE', 'NOTE', 'OTHER')", name='ck_evidencias_tipo'),
    sa.CheckConstraint('version_documento_id IS NULL OR documento_id IS NOT NULL', name='ck_evidencias_version_requiere_documento'),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrada_por_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_documento_id'], ['versiones_documento.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key', name='uq_evidencias_storage_key')
    )
    op.create_index('ix_evidencias_auditoria_tipo', 'evidencias', ['auditoria_id', 'tipo'], unique=False)
    op.create_index('ix_evidencias_documento', 'evidencias', ['documento_id'], unique=False)
    op.create_index('ix_evidencias_registrada_por', 'evidencias', ['registrada_por_id'], unique=False)
    op.create_index('ix_evidencias_sha256', 'evidencias', ['sha256'], unique=False)
    op.create_index('ix_evidencias_version', 'evidencias', ['version_documento_id'], unique=False)
    op.create_table('rondas_aprobacion',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('version_documento_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('numero_ronda', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('estado', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('solicitada_por_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('solicitada_en', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('resuelta_en', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("estado IN ('PENDING', 'IN_REVIEW') OR resuelta_en IS NOT NULL", name='ck_rondas_terminal_resuelta'),
    sa.CheckConstraint("estado IN ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'CANCELLED')", name='ck_rondas_estado'),
    sa.CheckConstraint('numero_ronda >= 1', name='ck_rondas_numero_positivo'),
    sa.ForeignKeyConstraint(['solicitada_por_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_documento_id'], ['versiones_documento.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_documento_id', 'numero_ronda', name='uq_rondas_version_numero')
    )
    op.create_index('ix_rondas_solicitada_por', 'rondas_aprobacion', ['solicitada_por_id'], unique=False)
    op.create_index('ix_rondas_version_estado', 'rondas_aprobacion', ['version_documento_id', 'estado'], unique=False)
    op.create_table('decisiones_aprobacion',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ronda_aprobacion_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('aprobador_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('estado', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('asignada_en', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('decidida_en', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("(estado = 'PENDING' AND decidida_en IS NULL) OR (estado <> 'PENDING' AND decidida_en IS NOT NULL)", name='ck_decisiones_fecha_estado'),
    sa.CheckConstraint("estado IN ('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED')", name='ck_decisiones_estado'),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ronda_aprobacion_id'], ['rondas_aprobacion.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ronda_aprobacion_id', 'aprobador_id', name='uq_decisiones_ronda_aprobador')
    )
    op.create_index('ix_decisiones_aprobador_estado', 'decisiones_aprobacion', ['aprobador_id', 'estado'], unique=False)
    op.create_table('hallazgos_evidencias',
    sa.Column('hallazgo_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('evidencia_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('vinculada_por_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('vinculada_en', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidencia_id'], ['evidencias.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgos.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vinculada_por_id'], ['usuarios.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('hallazgo_id', 'evidencia_id')
    )
    op.create_index('ix_hallazgos_evidencias_evidencia', 'hallazgos_evidencias', ['evidencia_id', 'hallazgo_id'], unique=False)
    op.create_index('ix_hallazgos_evidencias_vinculada_por', 'hallazgos_evidencias', ['vinculada_por_id'], unique=False)
    op.create_foreign_key(
        'fk_documentos_version_vigente',
        'documentos',
        'versiones_documento',
        ['version_vigente_id'],
        ['id'],
        ondelete='RESTRICT',
        onupdate='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documentos_version_vigente', 'documentos', type_='foreignkey')
    op.drop_index('ix_hallazgos_evidencias_vinculada_por', table_name='hallazgos_evidencias')
    op.drop_index('ix_hallazgos_evidencias_evidencia', table_name='hallazgos_evidencias')
    op.drop_table('hallazgos_evidencias')
    op.drop_index('ix_decisiones_aprobador_estado', table_name='decisiones_aprobacion')
    op.drop_table('decisiones_aprobacion')
    op.drop_index('ix_rondas_version_estado', table_name='rondas_aprobacion')
    op.drop_index('ix_rondas_solicitada_por', table_name='rondas_aprobacion')
    op.drop_table('rondas_aprobacion')
    op.drop_index('ix_evidencias_version', table_name='evidencias')
    op.drop_index('ix_evidencias_sha256', table_name='evidencias')
    op.drop_index('ix_evidencias_registrada_por', table_name='evidencias')
    op.drop_index('ix_evidencias_documento', table_name='evidencias')
    op.drop_index('ix_evidencias_auditoria_tipo', table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index('ix_documentos_auditoria_version_doc', table_name='documentos_auditoria')
    op.drop_index('ix_documentos_auditoria_estado', table_name='documentos_auditoria')
    op.drop_index('ix_documentos_auditoria_documento', table_name='documentos_auditoria')
    op.drop_index('ix_documentos_auditoria_asociado_por', table_name='documentos_auditoria')
    op.drop_table('documentos_auditoria')
    op.drop_index('ix_versiones_documento_subido_por', table_name='versiones_documento')
    op.drop_index('ix_versiones_documento_sha256', table_name='versiones_documento')
    op.drop_table('versiones_documento')
    op.drop_index('ix_hallazgos_responsable_estado_limite', table_name='hallazgos')
    op.drop_index('ix_hallazgos_detectado_en', table_name='hallazgos')
    op.drop_index('ix_hallazgos_created_by', table_name='hallazgos')
    op.drop_index('ix_hallazgos_cerrado_por', table_name='hallazgos')
    op.drop_index('ix_hallazgos_auditoria_estado', table_name='hallazgos')
    op.drop_table('hallazgos')
    op.drop_index('ix_eventos_ocurrido_en', table_name='eventos_auditoria')
    op.drop_index('ix_eventos_entidad_fecha', table_name='eventos_auditoria')
    op.drop_index('ix_eventos_correlation_id', table_name='eventos_auditoria')
    op.drop_index('ix_eventos_actor_fecha', table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_index('ix_documentos_version_vigente', table_name='documentos')
    op.drop_index('ix_documentos_responsable', table_name='documentos')
    op.drop_index('ix_documentos_estado_area', table_name='documentos')
    op.drop_index('ix_documentos_created_by', table_name='documentos')
    op.drop_index('ix_documentos_area_id', table_name='documentos')
    op.drop_table('documentos')
    op.drop_index('ix_auditorias_updated_by', table_name='auditorias')
    op.drop_index('ix_auditorias_responsable', table_name='auditorias')
    op.drop_index('ix_auditorias_estado_inicio', table_name='auditorias')
    op.drop_index('ix_auditorias_created_by', table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index('ix_usuarios_rol', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('areas')
    # ### end Alembic commands ###
