<?php if (!isset($accessRows) || !user_has_role('ADMIN')) { http_response_code(403); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">ADMINISTRACIÓN</p><h1><?= $accessRow === null ? 'Solicitudes de acceso' : 'Revisar solicitud' ?></h1><p class="page-description">El acceso se concede únicamente después de tu aprobación y del establecimiento de contraseña.</p></div></div>
<?php if ($accessError !== null): ?><div class="notice notice-error" role="alert"><?= e($accessError) ?></div><?php endif; ?>
<?php if ($accessRow === null): ?>
<form method="get" class="list-filters"><input type="hidden" name="pagina" value="solicitudes_acceso"><div class="form-field"><label for="estado">Estado</label><select id="estado" name="estado"><?php foreach (['PENDING'=>'Pendientes','APPROVED'=>'Aprobadas','REJECTED'=>'Rechazadas','FULFILLED'=>'Cuenta creada'] as $key=>$label): ?><option value="<?= e($key) ?>" <?= $accessStatus === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><button class="button button-secondary">Consultar</button></form>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>
<?php foreach ($accessRows as $item): ?><tr><td><?= e($item['nombre']) ?></td><td><?= e($item['identifier']) ?></td><td><?= e(display_date($item['created_at'])) ?></td><td><a class="text-link" href="<?= e(page_url('solicitud_acceso', ['id'=>$item['id']])) ?>">Revisar</a></td></tr><?php endforeach; ?>
<?php if ($accessRows === []): ?><tr><td colspan="4">No hay solicitudes en este estado.</td></tr><?php endif; ?>
</tbody></table></div></section>
<nav class="form-actions" aria-label="Paginación"><?php if ($accessOffset > 0): ?><a class="text-link" href="<?= e(page_url('solicitudes_acceso', ['estado'=>$accessStatus,'offset'=>max(0,$accessOffset-50)])) ?>">Anterior</a><?php endif; ?><?php if (count($accessRows) === 50 && $accessOffset < 100000): ?><a class="text-link" href="<?= e(page_url('solicitudes_acceso', ['estado'=>$accessStatus,'offset'=>$accessOffset+50])) ?>">Siguiente</a><?php endif; ?></nav>
<?php else: ?>
<section class="panel"><div class="upload-body"><h2><?= e($accessRow['nombre']) ?></h2><p><?= e($accessRow['identifier']) ?></p><p><?= nl2br(e($accessRow['motivo'])) ?></p><p>Estado: <?= e($accessRow['status']) ?></p>
<?php if ($accessRow['status'] === 'PENDING'): ?>
<form method="post" action="<?= e(page_url('solicitud_acceso',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="approve"><div class="form-field"><label for="rol">Rol autorizado</label><select name="rol" id="rol" required><option value="">Selecciona explícitamente un rol</option><?php foreach ($accessRoles as $role): ?><option value="<?= e($role) ?>"><?= e($role) ?></option><?php endforeach; ?></select></div><div class="form-actions"><button class="button button-primary">Aprobar y enviar instrucciones</button></div></form>
<form method="post" action="<?= e(page_url('solicitud_acceso',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="reject"><div class="form-field"><label for="motivo">Motivo administrativo (opcional)</label><textarea id="motivo" name="motivo" maxlength="1000"></textarea></div><div class="form-actions"><button class="button button-secondary">Rechazar solicitud</button></div></form>
<?php else: ?><p>Resuelta por administrador #<?= e($accessRow['resolved_by']) ?> · <?= e(display_date($accessRow['resolved_at'])) ?></p><p>Rol aprobado: <?= e($accessRow['approved_role'] ?? '—') ?></p><p><?= e($accessRow['admin_reason'] ?? '') ?></p>
<?php if ($accessRow['status'] === 'APPROVED'): ?><form method="post" action="<?= e(page_url('solicitud_acceso',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="resend"><button class="button button-secondary">Reenviar instrucciones iniciales</button></form><?php endif; ?>
<?php endif; ?></div></section><p class="context-note"><a href="<?= e(page_url('solicitudes_acceso')) ?>">Volver a solicitudes</a></p>
<?php endif; ?>
