<?php if (!isset($route)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">REVISIÓN DOCUMENTAL</p><h1>Análisis documental</h1><p class="page-description">Reglas explicables sobre recursos autorizados. Cada señal requiere interpretación humana.</p></div><a class="button button-secondary" href="<?= e(page_url('dashboard')) ?>">Volver al dashboard</a></div>
<?php if ($analysisSummary !== null && $analysisSummary['ok']): $summary=$analysisSummary['data']; ?>
<section class="metrics dashboard-metrics" aria-label="Resumen de análisis"><div class="metric"><h2>Señales documentales</h2><p class="metric-value"><?= e($summary['total']) ?></p><p class="metric-note">Total de reglas SQL, sin storage ni similitud local</p></div><?php foreach ($summary['por_severidad'] as $level=>$count): ?><div class="metric"><h2><?= e($level) ?></h2><p class="metric-value"><?= e($count) ?></p></div><?php endforeach; ?></section>
<?php elseif ($analysisSummary !== null): ?><div class="notice" role="status"><p>Resumen no disponible. <?= e($analysisSummary['message']) ?></p></div><?php endif; ?>
<section class="panel dashboard-alerts" aria-label="Consulta de análisis">
<form class="list-filters" method="get" action="index.php"><input type="hidden" name="pagina" value="analisis"><div class="form-field"><label for="analysis-severity">Severidad</label><select id="analysis-severity" name="severidad"><option value="">Todas</option><?php foreach (['INFO'=>'INFO · Información','WARNING'=>'WARNING · Atención'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($analysisFilters['severidad'] ?? '')===$value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="form-field"><label for="analysis-type">Tipo</label><select id="analysis-type" name="tipo"><option value="">Todos</option><?php foreach (analysis_types() as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($analysisFilters['tipo'] ?? '')===$value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div>
<div class="form-field"><label for="analysis-document">Documento ID</label><input id="analysis-document" name="documento_id" inputmode="numeric" value="<?= e($analysisFilters['documento_id'] ?? '') ?>"></div>
<?php if (can_show_action('auditorias')): ?><div class="form-field"><label for="analysis-audit">Auditoría ID</label><input id="analysis-audit" name="auditoria_id" inputmode="numeric" value="<?= e($analysisFilters['auditoria_id'] ?? '') ?>"></div><?php endif; ?>
<?php if (isset($analysisFilters['version_id'])): ?><input type="hidden" name="version_id" value="<?= e($analysisFilters['version_id']) ?>"><?php endif; ?>
<div class="filter-actions"><button class="button button-primary" type="submit">Consultar análisis</button><a class="text-link" href="<?= e(page_url('analisis')) ?>">Limpiar filtros</a></div></form>
<?php if (!$analysisResult['ok']): ?><div class="empty-state" role="status"><h2>Información no disponible</h2><p><?= e($analysisResult['message']) ?></p></div><?php else: ?>
<div class="panel-heading"><h2>Resultados autorizados</h2><p><?= e($analysisData['total']) ?> señales SQL</p></div>
<?php $analysisItems=$analysisData['items']; require __DIR__.'/../includes/analisis_list.php'; ?>
<nav class="panel-footer dashboard-pagination" aria-label="Páginas de análisis"><?php $params=array_diff_key($analysisFilters,array_flip(['limit','offset'])); $offset=$analysisFilters['offset']; if ($offset>0): ?><a class="button button-secondary" href="<?= e(page_url('analisis',$params+['offset'=>max(0,$offset-20)])) ?>">Anteriores</a><?php endif; ?><?php if ($offset+20<$analysisData['total'] && $offset+20<=10000): ?><a class="button button-secondary" href="<?= e(page_url('analisis',$params+['offset'=>$offset+20])) ?>">Siguientes</a><?php endif; ?></nav>
<?php if ($analysisDetail): $detail=$analysisResult['data']; ?><div class="panel-heading"><h2>Comprobaciones locales del recurso</h2></div><p class="section-note">Disponibilidad comprobada en <?= e($detail['versiones_comprobadas']) ?> versiones (límite <?= e($detail['versiones_comprobadas_limite']) ?>). <?= $detail['comprobacion_completa'] ? 'Alcance completo de versiones visibles.' : 'Alcance parcial: se alcanzó el límite.' ?> Similitud sobre la última versión visible: <?= e($detail['candidatos_comparados']) ?> candidatos (límite <?= e($detail['candidatos_limite']) ?>). <?= $detail['candidatos_truncados'] ? 'Candidatos truncados; no es exhaustivo.' : '' ?></p><?php $analysisItems=$detail['comprobaciones_locales']; require __DIR__.'/../includes/analisis_list.php'; ?><?php endif; ?>
<?php endif; ?></section>
<p class="context-note">Las coincidencias de SHA-256 describen igualdad binaria registrada. La similitud de nombres es una señal matemática; no prueba duplicidad. No hay detección de fraude, IA generativa ni catálogo de documentos obligatorios. Las comprobaciones de storage y nombres solo se realizan al analizar un documento o versión.</p>
