<?php if (!isset($states)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">CONTROL DOCUMENTAL</p><h1><?= e($page==='aprobacion'?'Ronda #'.$round['numero_ronda']:($page==='aprobacion_nueva'?'Nueva ronda de aprobación':'Aprobaciones')) ?></h1><p class="page-description">Decisiones verificables sobre una versión documental.</p></div><div class="document-actions"><?php if ($page==='aprobaciones' && can_show_action('aprobacion_gestionar')): ?><a class="button button-primary" href="<?= e(page_url('aprobacion_nueva',array_filter(array_intersect_key($filters,array_flip(['auditoria_id','documento_id']))))) ?>">Crear ronda</a><?php endif; ?><?php if ($page!=='aprobaciones'): ?><a class="button button-secondary" href="<?= e(page_url('aprobaciones')) ?>">Volver a aprobaciones</a><?php endif; ?></div></div>
<?php if (is_string($successMessage)): ?><div class="notice notice-success" role="status"><?= e($successMessage) ?></div><?php endif; ?>
<?php if ($formError!==null): ?><div class="notice notice-error" role="alert"><?= e($formError) ?></div><?php endif; ?>
<?php if ($page==='aprobaciones'): ?>
<section class="panel audit-list approval-list"><form class="list-filters" action="index.php" method="get"><input type="hidden" name="pagina" value="aprobaciones">
<?php foreach (['q'=>'Título del documento','documento_id'=>'ID de documento','auditoria_id'=>'ID de auditoría'] as $key=>$label): ?><div class="form-field"><label for="approval-<?= e($key) ?>"><?= e($label) ?></label><input id="approval-<?= e($key) ?>" name="<?= e($key) ?>" value="<?= e($filters[$key]) ?>"<?= $key==='q'?' maxlength="100"':' type="number" min="1"' ?>></div><?php endforeach; ?>
<?php foreach (['estado'=>$states,'orden'=>['-id'=>'Más recientes','id'=>'Más antiguas'],'pendientes_propias'=>['true'=>'Mis decisiones pendientes']] as $key=>$options): ?><div class="form-field"><label for="approval-<?= e($key) ?>"><?= e(['estado'=>'Estado','orden'=>'Orden','pendientes_propias'=>'Asignación'][$key]) ?></label><select id="approval-<?= e($key) ?>" name="<?= e($key) ?>"><option value="">Todas</option><?php foreach ($options as $value=>$label): ?><option value="<?= e($value) ?>"<?= $filters[$key]===$value?' selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><?php endforeach; ?>
<div class="filter-actions"><button class="button button-secondary" type="submit">Aplicar filtros</button><a class="text-link" href="<?= e(page_url('aprobaciones')) ?>">Limpiar</a></div></form>
<div class="panel-heading"><h2>Rondas registradas</h2><span class="record-count"><?= e($approvalCount) ?> registros · Página <?= e($pageNumber) ?> de <?= e($pageCount) ?></span></div>
<?php require __DIR__.'/aprobaciones_list.php'; approval_pagination('aprobaciones',array_filter($filters),'p',$pageNumber,$approvalResult); ?></section>
<?php elseif ($page==='aprobacion_nueva'): ?>
<section class="panel new-document-panel"><div class="panel-heading"><h2>Versión y aprobadores</h2></div><div class="upload-body"><p class="page-description">La ronda empieza pendiente. Todas las personas asignadas deben decidir antes del cierre automático.</p>
<form class="approval-create" method="post" action="<?= e(page_url('aprobacion_nueva',$context+['rp'=>$resourcePage,'ap'=>$approverPage])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>">
<div class="form-field"><label for="version_documento_id">Versión documental</label><select id="version_documento_id" name="version_documento_id" required><option value="">Selecciona una versión</option><?php foreach ($resourceResult['data'] as $candidate): ?><option value="<?= e($candidate['version_documento_id']) ?>"<?= (string)$candidate['version_documento_id']===$selectedVersion?' selected':'' ?>><?= e($candidate['documento_titulo']) ?> · v<?= e($candidate['numero_version']) ?></option><?php endforeach; ?></select></div>
<fieldset class="approval-assignments"><legend>Aprobadores activos</legend><?php foreach ($approverResult['data'] as $candidate): ?><label for="approver-<?= e($candidate['id']) ?>"><input type="checkbox" id="approver-<?= e($candidate['id']) ?>" name="aprobadores_ids[]" value="<?= e($candidate['id']) ?>"<?= in_array((string)$candidate['id'],$selectedApprovers,true)?' checked':'' ?>> <?= e($candidate['nombre']) ?></label><?php endforeach; ?><?php if ($approverResult['data']===[]): ?><p>No hay aprobadores elegibles en esta página.</p><?php endif; ?></fieldset>
<div class="form-actions"><button class="button button-primary" type="submit"<?= $resourceResult['data']===[] || $approverResult['data']===[]?' disabled':'' ?>>Crear ronda</button></div></form>
<p class="field-help">Los catálogos se consultan por páginas de veinte. Cambiar de página reinicia la selección del formulario.</p>
<h3>Versiones: página <?= e($resourcePage) ?></h3><?php approval_pagination('aprobacion_nueva',$context+['ap'=>$approverPage],'rp',$resourcePage,$resourceResult); ?>
<h3>Aprobadores: página <?= e($approverPage) ?></h3><?php approval_pagination('aprobacion_nueva',$context+['rp'=>$resourcePage],'ap',$approverPage,$approverResult); ?>
</div></section>
<?php else: ?>
<section class="panel"><div class="panel-heading"><h2><?= e($round['documento_titulo']) ?> · v<?= e($round['numero_version']) ?></h2><span class="badge badge-neutral"><?= e($states[$round['estado']]) ?></span></div><dl class="document-info"><div><dt>Solicitada por</dt><dd><?= e($round['solicitada_por']['nombre']) ?></dd></div><div><dt>Solicitada el</dt><dd><?= e(display_date($round['solicitada_en'])) ?></dd></div><div><dt>Resuelta el</dt><dd><?= e(display_date($round['resuelta_en'])) ?></dd></div><div><dt>Decisiones confirmadas</dt><dd><?= e($round['decisiones_count']-$round['pendientes_count']) ?> de <?= e($round['decisiones_count']) ?></dd></div></dl><div class="upload-body"><a class="text-link" href="<?= e(page_url('documento',['id'=>$round['documento_id']])) ?>">Consultar documento y versión</a></div></section>
<?php if (($round['puede_gestionar']??false) && can_show_action('aprobacion_gestionar')): ?><section class="panel"><div class="panel-heading"><h2>Gestión de la ronda</h2></div><div class="upload-body form-actions"><?php $commands=$round['estado']==='PENDING'?['iniciar'=>'Iniciar revisión','cancelar'=>'Cancelar ronda']:['cancelar'=>'Cancelar ronda']; if ($round['estado']==='IN_REVIEW' && $round['pendientes_count']===0) $commands['finalizar']='Finalizar ronda'; foreach ($commands as $command=>$label): ?><form method="post" action="<?= e(page_url('aprobacion',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="<?= e($command) ?>"><input type="hidden" name="estado_esperado" value="<?= e($round['estado']) ?>"><input type="hidden" name="updated_at_esperado" value="<?= e($round['updated_at']) ?>"><button class="button button-secondary" type="submit"><?= e($label) ?></button></form><?php endforeach; ?></div></section><?php endif; ?>
<?php if (($round['puede_decidir']??false) && can_show_action('aprobacion_decidir')): ?><section class="panel"><div class="panel-heading"><h2>Registrar mi decisión</h2></div><div class="upload-body"><p>La decisión confirmada queda registrada y no podrá editarse.</p><form class="approval-vote" method="post" action="<?= e(page_url('aprobacion',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="decision"><input type="hidden" name="updated_at_esperado" value="<?= e($round['mi_decision']['updated_at']) ?>"><div class="form-grid"><div class="form-field"><label for="decision-estado">Decisión</label><select id="decision-estado" name="estado" required><option value="">Selecciona una decisión</option><?php foreach (['APPROVED','REJECTED','CHANGES_REQUESTED'] as $value): ?><option value="<?= e($value) ?>"><?= e($states[$value]) ?></option><?php endforeach; ?></select></div><div class="form-field"><label for="comentario">Comentario</label><textarea id="comentario" name="comentario" rows="4" maxlength="16000"></textarea></div></div><div class="form-actions"><button class="button button-primary" type="submit">Confirmar decisión</button></div></form></div></section>
<?php elseif (is_array($round['mi_decision']??null)): ?><section class="panel"><div class="panel-heading"><h2>Mi decisión</h2></div><div class="upload-body"><p><?= e($states[$round['mi_decision']['estado']]??'Pendiente') ?></p><p class="preserve-lines"><?= e($round['mi_decision']['comentario']??'') ?></p></div></section><?php endif; ?>
<section class="panel audit-list"><div class="panel-heading"><h2>Asignaciones y decisiones</h2></div><?php if (!$decisionsResult['ok']): ?><div class="upload-body" role="status">No fue posible cargar las decisiones.</div><?php else: ?><div class="table-scroll" tabindex="0" role="region" aria-label="Decisiones de la ronda"><table class="data-table"><thead><tr><th>Aprobador</th><th>Decisión</th><th>Fecha</th><th>Comentario</th></tr></thead><tbody><?php foreach ($decisionsResult['data'] as $decision): ?><tr><td data-label="Aprobador"><?= e($decision['aprobador']['nombre']) ?></td><td data-label="Decisión"><?= e($states[$decision['estado']]) ?></td><td data-label="Fecha"><?= e(display_date($decision['decidida_en'])) ?></td><td data-label="Comentario" class="preserve-lines"><?= e($decision['comentario']??'') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><?php approval_pagination('aprobacion',['id'=>$recordId,'hp'=>$historyPage],'dp',$decisionPage,$decisionsResult); ?></section>
<section class="panel audit-history"><div class="panel-heading"><h2>Historial de la ronda</h2></div><div class="upload-body"><?php if (!$approvalHistory['ok']): ?><p role="status">No fue posible cargar el historial.</p><?php elseif ($approvalHistory['data']===[]): ?><p>No hay eventos en esta página.</p><?php else: ?><ol class="audit-events"><?php foreach ($approvalHistory['data'] as $item): ?><li><strong><?= e(['CREACION_RONDA_APROBACION'=>'Creación de ronda','INICIO_RONDA_APROBACION'=>'Inicio de revisión','DECISION_APROBACION'=>'Decisión confirmada','CIERRE_RONDA_APROBACION'=>'Cierre de ronda'][$item['accion']]??'Evento de aprobación') ?></strong><p><?= e(display_date($item['ocurrido_en'])) ?> · Usuario #<?= e($item['actor_id']) ?></p></li><?php endforeach; ?></ol><?php endif; ?></div><?php approval_pagination('aprobacion',['id'=>$recordId,'dp'=>$decisionPage],'hp',$historyPage,$approvalHistory); ?></section>
<?php endif; ?>
