<?php if (!isset($auditResult)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">GESTIÓN DE AUDITORÍAS</p><h1>Auditorías</h1><p class="page-description">Consulta de alcance, responsables y fechas previstas.</p></div><?php if (can_show_action('auditoria_crear')): ?><a class="button button-primary" href="<?= e(page_url('auditoria_nueva')) ?>">Nueva auditoría</a><?php endif; ?></div>
<?php if (!$userResult['ok']): ?><div class="notice" role="status">No fue posible consultar los nombres de los usuarios. Se muestran sus identificadores.</div><?php endif; ?>
<section class="panel"><?php list_filters('auditorias', $filterValues, ['estado' => ['label' => 'Estado', 'all' => 'Todos los estados', 'options' => $stateOptions]], 'Buscar por código o nombre'); ?><div class="panel-heading"><h2>Auditorías registradas</h2><?php if ($auditResult['ok']): ?><span class="record-count"><?= e(count($audits)) ?> de <?= e($auditCount) ?> registros</span><?php endif; ?></div>
<?php if (!$auditResult['ok']): ?><div class="empty-state" role="status"><h3>No fue posible cargar las auditorías.</h3><p>Intenta nuevamente en unos momentos.</p><a class="button button-secondary" href="<?= e(page_url('auditorias')) ?>">Volver a intentar</a></div>
<?php elseif ($audits === []): ?><div class="empty-state"><h3><?= $auditCount === 0 ? 'No hay auditorías registradas.' : 'No hay auditorías que coincidan con los filtros.' ?></h3><p><?= $auditCount === 0 ? 'Las auditorías disponibles para tu cuenta aparecerán aquí.' : 'Prueba otra búsqueda o limpia los filtros.' ?></p><a class="button button-secondary" href="<?= e(page_url($auditCount === 0 && can_show_action('auditoria_crear') ? 'auditoria_nueva' : 'auditorias')) ?>"><?= $auditCount === 0 && can_show_action('auditoria_crear') ? 'Nueva auditoría' : 'Limpiar filtros' ?></a></div>
<?php else: ?><div class="table-scroll" role="region" aria-label="Listado de auditorías" tabindex="0"><table class="data-table"><thead><tr><th scope="col">Código</th><th scope="col">Nombre</th><th scope="col">Estado</th><th scope="col">Inicio previsto</th><th scope="col">Fin previsto</th><th scope="col">Responsable</th><th scope="col" class="action-cell">Acciones</th></tr></thead><tbody>
<?php foreach ($audits as $row): [$label, $badge] = audit_status($row['estado'] ?? null); $id = positive_id($row['id'] ?? null); ?>
<tr><td class="document-code"><?= e($row['codigo'] ?? '') ?></td><td class="document-title"><?= e($row['nombre'] ?? '') ?></td><td><span class="badge badge-<?= e($badge) ?>"><?= e($label) ?></span></td><td class="date-cell"><?= e(calendar_date($row['fecha_inicio_prevista'] ?? null)) ?></td><td class="date-cell"><?= e(calendar_date($row['fecha_fin_prevista'] ?? null)) ?></td><td><?= e(user_name($row['responsable_id'] ?? null, $userNames)) ?></td><td class="action-cell"><?php if ($id !== null): ?><a class="table-link" href="<?= e(page_url('auditoria', ['id' => $id])) ?>">Ver detalle</a><?php endif; ?></td></tr>
<?php endforeach; ?></tbody></table></div><?php endif; ?></section>
