<?php if (!isset($auditResult)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">GESTIÓN DE AUDITORÍAS</p><h1>Auditorías</h1><p class="page-description">Alcance, responsables y seguimiento del ciclo de vida.</p></div><?php if (can_show_action('auditoria_crear')): ?><a class="button button-primary" href="<?= e(page_url('auditoria_nueva')) ?>">Nueva auditoría</a><?php endif; ?></div>
<section class="panel audit-list">
<?php if (!$areaResult['ok']): ?><div class="notice" role="status">No fue posible cargar el catálogo de áreas. Los demás filtros siguen disponibles.</div><?php endif; ?>
<form class="list-filters" method="get" action="index.php"><input type="hidden" name="pagina" value="auditorias">
<div class="form-field filter-search"><label for="audit-q">Código o nombre</label><input id="audit-q" name="q" maxlength="100" value="<?= e($filterValues['q']) ?>"></div>
<div class="form-field"><label for="audit-state">Estado</label><select id="audit-state" name="estado"><option value="">Todos los estados</option><?php foreach ($stateOptions as $key=>$name): ?><option value="<?= e($key) ?>"<?= $filterValues['estado']===$key ? ' selected' : '' ?>><?= e($name) ?></option><?php endforeach; ?></select></div>
<details class="audit-more-filters"<?= array_filter(array_intersect_key($filterValues,array_flip(['area_id','responsable_id','inicio_desde','inicio_hasta','orden']))) !== [] ? ' open' : '' ?>><summary>Más filtros</summary><div class="audit-filter-fields">
<div class="form-field"><label for="audit-area">Área documental vinculada</label><select id="audit-area" name="area_id"><option value="">Todas las áreas</option><?php foreach ($areaOptions as $key=>$name): ?><option value="<?= e($key) ?>"<?= $filterValues['area_id']===(string)$key ? ' selected' : '' ?>><?= e($name) ?></option><?php endforeach; ?></select></div>
<?php if (user_has_role('ADMIN')): ?><div class="form-field"><label for="audit-owner">Responsable</label><select id="audit-owner" name="responsable_id"><option value="">Todos los responsables</option><?php foreach ($ownerOptions as $key=>$name): ?><option value="<?= e($key) ?>"<?= $filterValues['responsable_id']===(string)$key ? ' selected' : '' ?>><?= e($name) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<div class="form-field"><label for="audit-from">Inicio previsto desde</label><input id="audit-from" type="date" name="inicio_desde" value="<?= e($filterValues['inicio_desde']) ?>"></div>
<div class="form-field"><label for="audit-to">Inicio previsto hasta</label><input id="audit-to" type="date" name="inicio_hasta" value="<?= e($filterValues['inicio_hasta']) ?>"></div>
<div class="form-field"><label for="audit-order">Orden</label><select id="audit-order" name="orden"><?php foreach (['id'=>'Más antiguas','-id'=>'Más recientes','fecha_inicio'=>'Inicio ascendente','-fecha_inicio'=>'Inicio descendente'] as $key=>$name): ?><option value="<?= e($key) ?>"<?= $filterValues['orden']===$key ? ' selected' : '' ?>><?= e($name) ?></option><?php endforeach; ?></select></div>
</div></details>
<div class="filter-actions"><button class="button button-secondary" type="submit">Aplicar filtros</button><a class="text-link" href="<?= e(page_url('auditorias')) ?>">Limpiar filtros</a></div></form>
<div class="panel-heading"><h2>Auditorías registradas</h2><?php if ($auditResult['ok']): ?><span class="record-count"><?= e($auditCount) ?> registros · Página <?= e($pageNumber) ?> de <?= e($pageCount) ?></span><?php endif; ?></div>
<?php if (!$auditResult['ok']): ?><div class="empty-state" role="status"><h3>No fue posible cargar las auditorías.</h3><p>Revisa los filtros e intenta nuevamente.</p></div>
<?php elseif ($audits===[]): ?><div class="empty-state"><h3>No hay auditorías que coincidan con los filtros.</h3><p>Las auditorías disponibles para tu cuenta aparecerán aquí.</p></div>
<?php else: ?><div class="table-scroll" role="region" aria-label="Listado de auditorías" tabindex="0"><table class="data-table"><thead><tr><th scope="col">Código / nombre</th><th scope="col">Estado</th><th scope="col">Inicio / fin previstos</th><th scope="col">Responsable</th><th scope="col">Áreas vinculadas</th><th scope="col">Acciones</th></tr></thead><tbody>
<?php foreach ($audits as $row): [$label,$badge]=audit_status($row['estado']??null);$id=positive_id($row['id']??null); ?>
<tr><td data-label="Auditoría"><strong><?= e($row['codigo']??'') ?></strong><br><?= e($row['nombre']??'') ?></td><td data-label="Estado"><span class="badge badge-<?= e($badge) ?>"><?= e($label) ?></span></td><td data-label="Fechas"><?= e(calendar_date($row['fecha_inicio_prevista']??null)) ?><br><?= e(calendar_date($row['fecha_fin_prevista']??null)) ?></td><td data-label="Responsable"><?= e($row['responsable']['nombre']??user_name($row['responsable_id']??null,$userNames)) ?></td><td data-label="Áreas"><?= e(implode(', ',array_column($row['areas']??[],'nombre')) ?: 'Sin documentos vinculados') ?></td><td data-label="Acciones"><?php if ($id!==null): ?><a class="table-link" href="<?= e(page_url('auditoria',['id'=>$id])) ?>">Ver detalle</a><?php endif; ?></td></tr>
<?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php if ($auditResult['ok']): ?><nav class="audit-pagination" aria-label="Paginación de auditorías"><?php if ($pageNumber>1): ?><a class="button button-secondary" href="<?= e(page_url('auditorias',array_filter($filterValues)+['p'=>$pageNumber-1])) ?>">Anterior</a><?php endif; ?><?php if ($pageNumber<$pageCount && $pageNumber<501): ?><a class="button button-secondary" href="<?= e(page_url('auditorias',array_filter($filterValues)+['p'=>$pageNumber+1])) ?>">Siguiente</a><?php endif; ?></nav><?php endif; ?></section>
