<?php if (!isset($auditResult)) { http_response_code(404); exit; } ?>
<?php if (!$auditResult['ok'] || $audit === null): ?><div class="page-heading"><h1>Auditoría</h1><a class="button button-secondary" href="<?= e(page_url('auditorias')) ?>">Volver a auditorías</a></div><section class="panel empty-state" role="status"><h2><?= $auditResult['ok'] ? 'La auditoría solicitada no existe.' : 'No fue posible consultar la auditoría.' ?></h2></section><?php return; endif; ?>
<?php [$label, $badge] = audit_status($audit['estado'] ?? null); ?>
<div class="page-heading"><div><p class="eyebrow"><?= e($audit['codigo'] ?? '') ?></p><h1><?= e($audit['nombre'] ?? '') ?></h1><div class="document-tags"><span class="badge badge-<?= e($badge) ?>"><?= e($label) ?></span></div></div><a class="button button-secondary" href="<?= e(page_url('auditorias')) ?>">Volver a auditorías</a></div>
<?php if (is_string($successMessage)): ?><div class="notice notice-success" role="status"><?= e($successMessage) ?></div><?php endif; ?>
<section class="panel document-section"><div class="panel-heading"><h2>Información general</h2></div><dl class="document-info"><div class="info-wide"><dt>Alcance</dt><dd class="preserve-lines"><?= e($audit['alcance'] ?? '') ?></dd></div>
<div><dt>Responsable</dt><dd><?= e(user_name($audit['responsable_id'] ?? null, $userNames)) ?></dd></div><div><dt>Creado por</dt><dd><?= e(user_name($audit['created_by_id'] ?? null, $userNames)) ?></dd></div>
<div><dt>Inicio previsto</dt><dd><?= e(calendar_date($audit['fecha_inicio_prevista'] ?? null)) ?></dd></div><div><dt>Fin previsto</dt><dd><?= e(calendar_date($audit['fecha_fin_prevista'] ?? null)) ?></dd></div>
<div><dt>Fecha de creación</dt><dd><?= e(display_date($audit['created_at'] ?? null)) ?></dd></div><div><dt>Última actualización</dt><dd><?= e(display_date($audit['updated_at'] ?? null)) ?></dd></div></dl></section>
<section class="panel"><div class="panel-heading"><h2>Evidencias</h2></div><div class="upload-body"><p class="page-description">Consulta las evidencias vinculadas a esta auditoría o registra una nueva.</p><div class="form-actions"><?php if (($audit['estado'] ?? '') !== 'CANCELLED'): ?><a class="button button-primary" href="<?= e(page_url('evidencia_archivo', ['auditoria_id' => $recordId])) ?>">Registrar archivo</a><a class="button button-secondary" href="<?= e(page_url('evidencia_logica', ['auditoria_id' => $recordId])) ?>">Registrar evidencia lógica</a><?php else: ?><span class="context-note">La auditoría está cancelada y no admite nuevas evidencias.</span><?php endif; ?><a class="text-link" href="<?= e(page_url('evidencias', ['auditoria_id' => $recordId])) ?>">Ver evidencias</a></div></div></section>
