<?php if (!isset($auditResult)) { http_response_code(404); exit; } ?>
<?php if (!$auditResult['ok'] || $audit===null): ?><div class="page-heading"><h1>Auditoría</h1><a class="button button-secondary" href="<?= e(page_url('auditorias')) ?>">Volver a auditorías</a></div><section class="panel empty-state" role="status"><h2>La auditoría solicitada no está disponible.</h2></section><?php return; endif; ?>
<?php [$label,$badge]=audit_status($audit['estado']??null); ?>
<div class="page-heading"><div><p class="eyebrow"><?= e($audit['codigo']??'') ?></p><h1><?= e($audit['nombre']??'') ?></h1><span class="badge badge-<?= e($badge) ?>"><?= e($label) ?></span></div><div class="document-actions"><?php if ($editable): ?><a class="button button-primary" href="<?= e(page_url('auditoria_editar',['id'=>$recordId])) ?>">Editar auditoría</a><?php endif; ?><a class="button button-secondary" href="<?= e(page_url('auditorias')) ?>">Volver a auditorías</a></div></div>
<?php if (is_string($successMessage)): ?><div class="notice notice-success" role="status"><?= e($successMessage) ?></div><?php endif; ?>
<?php if ($formError!==null): ?><div class="notice notice-error" role="alert"><?= e($formError) ?></div><?php endif; ?>
<section class="panel document-section"><div class="panel-heading"><h2>Información general</h2></div><dl class="document-info"><div class="info-wide"><dt>Alcance</dt><dd class="preserve-lines"><?= e($audit['alcance']??'') ?></dd></div><div><dt>Responsable</dt><dd><?= e($audit['responsable']['nombre']??user_name($audit['responsable_id']??null,$userNames)) ?></dd></div><div><dt>Áreas de documentos vinculados</dt><dd><?= e(implode(', ',array_column($audit['areas']??[],'nombre')) ?: 'Sin documentos vinculados') ?></dd></div><div><dt>Inicio previsto</dt><dd><?= e(calendar_date($audit['fecha_inicio_prevista']??null)) ?></dd></div><div><dt>Fin previsto</dt><dd><?= e(calendar_date($audit['fecha_fin_prevista']??null)) ?></dd></div><div><dt>Activada el</dt><dd><?= e(display_date($audit['iniciada_en']??null)) ?></dd></div><div><dt>Cerrada el</dt><dd><?= e(display_date($audit['completada_en']??null)) ?></dd></div><div><dt>Creado por</dt><dd><?= e(user_name($audit['created_by_id']??null,$userNames)) ?></dd></div><div><dt>Fecha de creación</dt><dd><?= e(display_date($audit['created_at']??null)) ?></dd></div><div><dt>Última actualización</dt><dd><?= e(display_date($audit['updated_at']??null)) ?></dd></div></dl></section>
<?php if (can_show_action('auditoria_estado')): $actions=['PLANNED'=>['IN_PROGRESS'=>'Activar auditoría'],'IN_PROGRESS'=>['IN_REVIEW'=>'Enviar a revisión'],'IN_REVIEW'=>['IN_PROGRESS'=>'Regresar a activa','COMPLETED'=>'Cerrar auditoría']][$audit['estado']??'']??[]; ?>
<section class="panel"><div class="panel-heading"><h2>Ciclo de vida</h2></div><div class="upload-body"><?php if ($actions===[]): ?><p>Esta auditoría es terminal y no admite cambios.</p><?php else: ?><p class="page-description">Cada cambio registra al actor y la fecha. El cierre es definitivo.</p><div class="form-actions"><?php foreach ($actions as $target=>$actionLabel): ?><form method="post" action="<?= e(page_url('auditoria',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="estado" value="<?= e($target) ?>"><input type="hidden" name="estado_esperado" value="<?= e($audit['estado']) ?>"><input type="hidden" name="updated_at_esperado" value="<?= e($audit['updated_at']??'') ?>"><button class="button button-secondary" type="submit"><?= e($actionLabel) ?></button></form><?php endforeach; ?></div><?php endif; ?></div></section>
<?php endif; ?>
<section class="panel"><div class="panel-heading"><h2>Evidencias</h2></div><div class="upload-body"><div class="form-actions"><?php if (can_show_action('evidencia_crear') && !in_array($audit['estado']??'', ['COMPLETED','CANCELLED'],true)): ?><a class="button button-primary" href="<?= e(page_url('evidencia_archivo',['auditoria_id'=>$recordId])) ?>">Registrar archivo</a><a class="button button-secondary" href="<?= e(page_url('evidencia_logica',['auditoria_id'=>$recordId])) ?>">Registrar evidencia lógica</a><?php else: ?><span class="context-note">Esta auditoría no admite nuevas evidencias.</span><?php endif; ?><a class="text-link" href="<?= e(page_url('evidencias',['auditoria_id'=>$recordId])) ?>">Ver evidencias</a></div></div></section>
<?php if (user_has_role('ADMIN')): ?><section class="panel audit-history"><div class="panel-heading"><h2>Historial de la auditoría</h2></div><div class="upload-body"><?php if (!$historyResult['ok']): ?><p role="status">No fue posible cargar el historial.</p><?php elseif ($historyResult['data']===[]): ?><p>No hay eventos registrados en esta página.</p><?php else: ?><ol class="audit-events"><?php foreach ($historyResult['data'] as $event): ?><li><strong><?= e(event_label($event['accion']??'')) ?></strong><p><?= e(display_date($event['ocurrido_en']??null)) ?> · Actor <?= e(user_name($event['actor_id']??null,$userNames)) ?></p><?php $newState=$event['datos_nuevos']['estado']??null;if (is_string($newState)): ?><span class="badge badge-neutral"><?= e(audit_status($newState)[0]) ?></span><?php endif; ?></li><?php endforeach; ?></ol><?php endif; ?><nav class="audit-pagination" aria-label="Paginación del historial"><?php if ($historyPage>1): ?><a class="text-link" href="<?= e(page_url('auditoria',['id'=>$recordId,'hp'=>$historyPage-1])) ?>">Más recientes</a><?php endif; ?><?php if (count($historyResult['data'])===20 && $historyPage<501): ?><a class="text-link" href="<?= e(page_url('auditoria',['id'=>$recordId,'hp'=>$historyPage+1])) ?>">Más antiguos</a><?php endif; ?></nav></div></section><?php endif; ?>
<section class="panel audit-list"><div class="panel-heading"><h2>Hallazgos de la auditoría</h2><span class="record-count"><?= e($findingResult['total']??count($findingResult['data'])) ?> hallazgos</span></div>
<?php require __DIR__.'/hallazgos_list.php'; ?>
<div class="upload-body form-actions"><?php if (can_show_action('hallazgo_gestionar') && in_array($audit['estado']??'', ['IN_PROGRESS','IN_REVIEW'],true)): ?><a class="button button-primary" href="<?= e(page_url('hallazgo_nuevo',['auditoria_id'=>$recordId])) ?>">Crear hallazgo</a><?php endif; ?><a class="text-link" href="<?= e(page_url('hallazgos',['auditoria_id'=>$recordId])) ?>">Ver todos los hallazgos</a></div></section>
