<?php if (!isset($route)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">SEGUIMIENTO OPERATIVO</p><h1>Alertas derivadas</h1><p class="page-description">Condiciones registradas en los recursos autorizados.</p></div><a class="button button-secondary" href="<?= e(page_url('dashboard')) ?>">Volver al resumen ejecutivo</a></div>
<section class="panel dashboard-alerts" aria-label="Consulta de alertas">
<form class="list-filters" method="get" action="index.php"><input type="hidden" name="pagina" value="alertas"><div class="form-field"><label for="alert-severity">Severidad</label><select id="alert-severity" name="severidad"><option value="">Todas</option><?php foreach (['INFO'=>'INFO · Información','WARNING'=>'WARNING · Atención'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($alertFilters['severidad'] ?? '')===$value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="form-field"><label for="alert-type">Tipo</label><select id="alert-type" name="tipo"><option value="">Todos</option><?php foreach (dashboard_alert_types() as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($alertFilters['tipo'] ?? '')===$value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="filter-actions"><button class="button button-primary" type="submit">Filtrar alertas</button><a class="text-link" href="<?= e(page_url('alertas')) ?>">Limpiar filtros</a></div></form>
<?php if (!$dashboardResult['ok']): ?><div class="empty-state" role="status"><h2>Información no disponible</h2><p><?= e($dashboardResult['message']) ?></p></div><?php else: ?>
<div class="panel-heading"><h2>Resultados autorizados</h2><p><?= e($alertData['total']) ?> alertas</p></div>
<?php require __DIR__.'/../includes/dashboard_alert_list.php'; ?>
<nav class="panel-footer dashboard-pagination" aria-label="Páginas de alertas"><?php $params=array_diff_key($alertFilters,array_flip(['limit','offset'])); if ($alertOffset>0): ?><a class="button button-secondary" href="<?= e(page_url('alertas',$params+['offset'=>max(0,$alertOffset-20)])) ?>">Alertas anteriores</a><?php endif; ?><?php if ($alertOffset+20<$alertData['total'] && $alertOffset+20<=10000): ?><a class="button button-secondary" href="<?= e(page_url('alertas',$params+['offset'=>$alertOffset+20])) ?>">Alertas siguientes</a><?php endif; ?></nav>
<?php endif; ?></section>
