<?php if (!isset($evidenceResult)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">REGISTRO PROBATORIO</p><h1>Evidencias</h1><p class="page-description">Registro y consulta de evidencias de auditoría.</p></div><div class="document-actions"><a class="button button-primary" href="<?= e(page_url('evidencia_archivo', $listQuery)) ?>">Registrar archivo</a><a class="button button-secondary" href="<?= e(page_url('evidencia_logica', $listQuery)) ?>">Registrar evidencia lógica</a></div></div>
<?php if (!$auditResult['ok']): ?><div class="notice" role="status">No fue posible consultar el catálogo de auditorías. Se muestran sus identificadores.</div><?php endif; ?>
<?php if ($auditFilter !== null && !isset($auditCodes[$auditFilter])) $auditCodes[$auditFilter] = 'Auditoría #' . $auditFilter; ?>
<section class="panel"><?php list_filters('evidencias', ['auditoria_id' => $auditFilter], ['auditoria_id' => ['label' => 'Auditoría', 'all' => 'Todas las auditorías', 'options' => $auditCodes]]); ?><div class="panel-heading"><h2>Evidencias registradas</h2><?php if ($evidenceResult['ok']): ?><span class="record-count"><?= e(count($evidences)) ?> registros en esta página</span><?php endif; ?></div>
<?php if (!$evidenceResult['ok']): ?><div class="empty-state" role="status"><h3><?= $filterInvalid ? 'El filtro o la página no son válidos.' : 'No fue posible cargar las evidencias.' ?></h3><p><?= $filterInvalid ? 'Selecciona una auditoría y vuelve a consultar.' : 'Intenta nuevamente en unos momentos.' ?></p><a class="button button-secondary" href="<?= e(page_url('evidencias', $listQuery)) ?>">Volver a intentar</a></div>
<?php elseif ($evidences === []): ?><div class="empty-state" role="status"><h3><?= $offset > 0 ? 'No hay más evidencias en esta página.' : ($auditFilter !== null ? 'No hay evidencias para esta auditoría.' : 'No hay evidencias registradas.') ?></h3><p>Los archivos y las evidencias lógicas aparecerán aquí después de registrarlos.</p><?php if ($offset > 0): ?><a class="button button-secondary" href="<?= e(page_url('evidencias', $listQuery)) ?>">Volver al inicio del listado</a><?php endif; ?></div>
<?php else: ?><div class="table-scroll" role="region" aria-label="Listado de evidencias" tabindex="0"><table class="data-table"><thead><tr><th scope="col">ID</th><th scope="col">Título</th><th scope="col">Tipo</th><th scope="col">Auditoría</th><th scope="col">Documento / versión</th><th scope="col">Fecha</th><th scope="col" class="action-cell">Acciones</th></tr></thead><tbody>
<?php foreach ($evidences as $row): $id = positive_id($row['id'] ?? null); $auditId = positive_id($row['auditoria_id'] ?? null); $docId = positive_id($row['documento_id'] ?? null); ?>
<tr><td><?= e($id) ?></td><td class="document-title"><?= e($row['titulo'] ?? '') ?></td><td><span class="badge badge-neutral"><?= e(evidence_type($row['tipo'] ?? null)) ?></span></td><td><?php if ($auditId !== null): ?><a class="text-link" href="<?= e(page_url('auditoria', ['id' => $auditId])) ?>"><?= e($auditCodes[$auditId] ?? 'Auditoría #' . $auditId) ?></a><?php else: ?>—<?php endif; ?></td><td><?php if ($docId !== null): ?><a class="text-link" href="<?= e(page_url('documento', ['id' => $docId])) ?>">Documento #<?= e($docId) ?></a><br><?= e(isset($row['version_documento_id']) ? 'Versión ID #' . $row['version_documento_id'] : 'Sin versión específica') ?><?php else: ?>Sin vincular<?php endif; ?></td><td class="date-cell"><?= e(display_date($row['created_at'] ?? null)) ?></td><td class="action-cell"><?php if ($id !== null): ?><a class="table-link" href="<?= e(page_url('evidencia', ['id' => $id])) ?>">Ver detalle</a><?php if (($row['tipo'] ?? '') === 'FILE'): ?><br><a class="table-link" href="<?= e(page_url('evidencia', ['id' => $id, 'accion' => 'descargar'])) ?>">Descargar</a><?php endif; endif; ?></td></tr>
<?php endforeach; ?></tbody></table></div>
<?php endif; ?>
<?php if ($evidenceResult['ok'] && ($offset > 0 || $hasNext)): ?><nav class="upload-body document-actions" aria-label="Paginación de evidencias"><?php if ($offset > 0): ?><a class="button button-secondary" href="<?= e(page_url('evidencias', $listQuery + ['offset' => max(0, $offset - 50)])) ?>">Anterior</a><?php endif; ?><?php if ($hasNext): ?><a class="button button-secondary" href="<?= e(page_url('evidencias', $listQuery + ['offset' => $offset + 50])) ?>">Siguiente</a><?php endif; ?></nav><?php endif; ?></section>
