<?php if (!isset($evidenceResult)) { http_response_code(404); exit; } ?>
<?php if (!$evidenceResult['ok']): ?><div class="page-heading"><h1>Evidencia</h1><a class="button button-secondary" href="<?= e(page_url('evidencias')) ?>">Volver a evidencias</a></div><section class="panel empty-state" role="status"><h2><?= $evidenceResult['status'] === 404 ? 'La evidencia solicitada no existe.' : 'No fue posible consultar la evidencia.' ?></h2></section><?php return; endif; ?>
<div class="page-heading"><div><p class="eyebrow">EVIDENCIA #<?= e($recordId) ?></p><h1><?= e($evidence['titulo'] ?? '') ?></h1><div class="document-tags"><span class="badge badge-neutral"><?= e(evidence_type($evidence['tipo'] ?? null)) ?></span></div></div><a class="button button-secondary" href="<?= e(page_url('evidencias')) ?>">Volver a evidencias</a></div>
<?php if (is_string($successMessage)): ?><div class="notice notice-success" role="status"><?= e($successMessage) ?></div><?php endif; ?>
<?php if ($downloadError !== null): ?><div class="notice notice-error" role="alert"><?= e($downloadError) ?></div><?php endif; ?>
<?php if (($evidence['tipo'] ?? '') === 'FILE'): ?><div class="document-actions"><a class="button button-primary" href="<?= e(page_url('evidencia', ['id' => $recordId, 'accion' => 'descargar'])) ?>">Descargar archivo</a></div><?php endif; ?>
<section class="panel"><div class="panel-heading"><h2>Información general</h2></div><dl class="document-info"><div class="info-wide"><dt>Descripción</dt><dd class="preserve-lines"><?= e($evidence['descripcion'] ?? 'Sin descripción registrada.') ?></dd></div>
<div><dt>Auditoría</dt><dd><?php $auditId = positive_id($evidence['auditoria_id'] ?? null); if ($auditId !== null): ?><a class="text-link" href="<?= e(page_url('auditoria', ['id' => $auditId])) ?>">Auditoría #<?= e($auditId) ?></a><?php else: ?>—<?php endif; ?></dd></div><div><dt>Registrada por</dt><dd><?= e(user_name($evidence['registrada_por_id'] ?? null, $userNames)) ?></dd></div>
<div><dt>Fecha de registro</dt><dd><?= e(display_date($evidence['created_at'] ?? null)) ?></dd></div><div><dt>Última actualización</dt><dd><?= e(display_date($evidence['updated_at'] ?? null)) ?></dd></div>
<?php $docId = positive_id($evidence['documento_id'] ?? null); if ($docId !== null): ?><div><dt>Documento vinculado</dt><dd><a class="text-link" href="<?= e(page_url('documento', ['id' => $docId])) ?>">Documento #<?= e($docId) ?></a></dd></div><div><dt>ID de versión vinculada</dt><dd><?= e(positive_id($evidence['version_documento_id'] ?? null) ?? 'Sin versión específica') ?></dd></div><?php endif; ?>
<?php if (($evidence['tipo'] ?? '') === 'FILE'): ?><div><dt>Archivo</dt><dd><?= e($evidence['nombre_original'] ?? '') ?></dd></div><div><dt>Tamaño</dt><dd><?= e(file_size_label($evidence['tamano_bytes'] ?? null)) ?></dd></div><div class="info-wide"><dt>SHA-256</dt><dd class="integrity-hash"><?= e($evidence['sha256'] ?? '') ?></dd></div><?php endif; ?>
<?php if (is_string($evidence['referencia_url'] ?? null) && $evidence['referencia_url'] !== ''): ?><div class="info-wide"><dt>Referencia</dt><dd><?= e($evidence['referencia_url']) ?></dd></div><?php endif; ?>
</dl></section>
