<?php if (!isset($finding)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">HALLAZGO #<?= e($finding['numero']??'') ?> · <?= e($audit['codigo']??'') ?></p><h1><?= e($finding['titulo']??'') ?></h1><span class="badge badge-neutral"><?= e(finding_states()[$finding['estado']]??'') ?></span></div><div class="document-actions"><?php if ($mutable): ?><a class="button button-primary" href="<?= e(page_url('hallazgo_editar',['id'=>$recordId])) ?>">Editar hallazgo</a><?php endif; ?><a class="button button-secondary" href="<?= e(page_url('auditoria',['id'=>$auditId])) ?>">Volver a auditoría</a></div></div>
<?php if (is_string($successMessage)): ?><div class="notice notice-success" role="status"><?= e($successMessage) ?></div><?php endif; ?>
<?php if ($formError!==null): ?><div class="notice notice-error" role="alert"><?= e($formError) ?></div><?php endif; ?>
<section class="panel"><div class="panel-heading"><h2>Información del hallazgo</h2></div><dl class="document-info"><div class="info-wide"><dt>Descripción</dt><dd class="preserve-lines"><?= e($finding['descripcion']??'') ?></dd></div><div><dt>Categoría</dt><dd><?= e($finding['categoria']??'') ?></dd></div><div><dt>Severidad</dt><dd><?= e(finding_severities()[$finding['severidad']]??'') ?></dd></div><div><dt>Responsable</dt><dd><?= e($finding['responsable']['nombre']??'Sin asignar') ?></dd></div><div><dt>Fecha límite</dt><dd><?= e(calendar_date($finding['fecha_limite']??null)) ?></dd></div><div><dt>Detectado el</dt><dd><?= e(display_date($finding['detectado_en']??null)) ?></dd></div><div><dt>Creador</dt><dd><?= e(user_name($finding['created_by_id']??null,$userNames)) ?></dd></div><div><dt>Cerrado el</dt><dd><?= e(display_date($finding['cerrado_en']??null)) ?></dd></div><div><dt>Última actualización</dt><dd><?= e(display_date($finding['updated_at']??null)) ?></dd></div><div class="info-wide"><dt>Resolución</dt><dd class="preserve-lines"><?= e($finding['resolucion']??'Sin resolución registrada') ?></dd></div></dl></section>
<?php if ($mutable): $targets=['OPEN'=>['IN_PROGRESS'],'IN_PROGRESS'=>['PENDING_VERIFICATION'],'PENDING_VERIFICATION'=>['IN_PROGRESS','CLOSED']][$finding['estado']]??[]; if (user_has_role('ADMIN')) $targets[]='ACCEPTED_RISK'; ?>
<section class="panel"><div class="panel-heading"><h2>Cambiar estado</h2></div><div class="upload-body"><form method="post" action="<?= e(page_url('hallazgo',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="estado"><input type="hidden" name="estado_esperado" value="<?= e($finding['estado']) ?>"><input type="hidden" name="updated_at_esperado" value="<?= e($finding['updated_at']) ?>"><div class="form-grid"><?php form_select('estado','Nuevo estado',array_intersect_key(finding_states(),array_flip($targets)),[],[]); form_control('resolucion','Resolución (obligatoria para cerrar o aceptar riesgo)',[],[],'textarea',false,16000); ?></div><div class="form-actions"><button type="submit" class="button button-secondary">Cambiar estado</button></div></form></div></section>
<?php endif; ?>
<section class="panel"><div class="panel-heading"><h2>Evidencias relacionadas</h2><span class="record-count"><?= e($linkedResult['total']??count($linkedResult['data'])) ?> evidencias</span></div><div class="upload-body">
<?php if (!$linkedResult['ok']): ?><p role="status">No fue posible cargar las evidencias.</p><?php elseif ($linkedResult['data']===[]): ?><p>Sin evidencias en esta página.</p><?php else: ?><ul class="finding-evidence"><?php foreach ($linkedResult['data'] as $row): ?><li><a class="text-link" href="<?= e(page_url('evidencia',['id'=>$row['id']])) ?>"><?= e($row['titulo']??'') ?></a> <span class="badge badge-neutral"><?= e(evidence_type($row['tipo']??null)) ?></span><?php if (($row['tipo']??'')==='FILE'): ?><p class="integrity-hash">SHA-256: <?= e($row['sha256']??'') ?></p><?php endif; ?></li><?php endforeach; ?></ul><?php endif; ?>
<nav class="audit-pagination" aria-label="Paginación de evidencias relacionadas"><?php if ($evidencePage>1): ?><a class="text-link" href="<?= e(page_url('hallazgo',['id'=>$recordId,'ep'=>$evidencePage-1])) ?>">Anterior</a><?php endif; ?><?php if (($linkedResult['total']??0)>$evidencePage*20 && $evidencePage<501): ?><a class="text-link" href="<?= e(page_url('hallazgo',['id'=>$recordId,'ep'=>$evidencePage+1])) ?>">Siguiente</a><?php endif; ?></nav>
<?php if ($mutable): ?><div class="form-actions"><a class="button button-secondary" href="<?= e(page_url('evidencia_archivo',['auditoria_id'=>$auditId,'hallazgo_id'=>$recordId])) ?>">Registrar archivo y asociar</a><a class="button button-secondary" href="<?= e(page_url('evidencia_logica',['auditoria_id'=>$auditId,'hallazgo_id'=>$recordId])) ?>">Registrar evidencia lógica y asociar</a></div><?php endif; ?>
</div></section>
<?php if ($mutable): ?><section class="panel"><div class="panel-heading"><h2>Asociar evidencia existente</h2></div><div class="upload-body">
<?php if (!$catalogResult['ok']): ?><p role="status">No fue posible cargar el catálogo de evidencias.</p><?php elseif ($catalogResult['data']===[]): ?><p>No hay evidencias disponibles en esta página.</p><?php else: ?><form method="post" action="<?= e(page_url('hallazgo',['id'=>$recordId])) ?>"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="accion" value="asociar"><div class="form-grid"><?php form_select('evidencia_id','Evidencia de esta auditoría',array_column($catalogResult['data'],'titulo','id'),[],[]); form_control('contexto','Contexto',[],[],'textarea',false,16000); ?></div><div class="form-actions"><button class="button button-primary" type="submit">Asociar evidencia</button></div></form><?php endif; ?>
<nav class="audit-pagination" aria-label="Paginación del catálogo de evidencias"><?php if ($catalogPage>1): ?><a class="text-link" href="<?= e(page_url('hallazgo',['id'=>$recordId,'cp'=>$catalogPage-1])) ?>">Anterior</a><?php endif; ?><?php if (($catalogResult['total']??0)>$catalogPage*20 && $catalogPage<501): ?><a class="text-link" href="<?= e(page_url('hallazgo',['id'=>$recordId,'cp'=>$catalogPage+1])) ?>">Siguiente</a><?php endif; ?></nav></div></section><?php endif; ?>
<?php if (user_has_role('ADMIN')): ?><section class="panel"><div class="panel-heading"><h2>Historial del hallazgo</h2></div><div class="upload-body"><?php if (!$historyResult['ok']): ?><p role="status">No fue posible cargar el historial.</p><?php else: ?><ol class="audit-events"><?php foreach ($historyResult['data'] as $event): ?><li><strong><?= e(event_label($event['accion']??'')) ?></strong><p><?= e(display_date($event['ocurrido_en']??null)) ?> · Actor <?= e(user_name($event['actor_id']??null,$userNames)) ?></p><?php if (isset($event['datos_nuevos']['estado'])): ?><p><?= e(finding_states()[$event['datos_nuevos']['estado']]??'') ?></p><?php endif; ?></li><?php endforeach; ?></ol><?php endif; ?><nav class="audit-pagination" aria-label="Paginación del historial"><?php if ($historyPage>1): ?><a class="text-link" href="<?= e(page_url('hallazgo',['id'=>$recordId,'hp'=>$historyPage-1])) ?>">Más recientes</a><?php endif; ?><?php if (($historyResult['total']??0)>$historyPage*20 && $historyPage<501): ?><a class="text-link" href="<?= e(page_url('hallazgo',['id'=>$recordId,'hp'=>$historyPage+1])) ?>">Más antiguos</a><?php endif; ?></nav></div></section><?php endif; ?>
