<?php if (!isset($findingResult)) { http_response_code(404); exit; } ?>
<div class="page-heading"><div><p class="eyebrow">SEGUIMIENTO DE AUDITORÍAS</p><h1>Hallazgos</h1><p class="page-description">Consulta el estado, la severidad y las evidencias de cada hallazgo.</p></div></div>
<section class="panel audit-list finding-list">
<form class="list-filters" method="get" action="index.php"><input type="hidden" name="pagina" value="hallazgos">
<?php foreach (['q'=>'Título o descripción','auditoria_id'=>'ID de auditoría','responsable_id'=>'ID de responsable'] as $key=>$label): ?><div class="form-field"><label for="finding-<?= e($key) ?>"><?= e($label) ?></label><input id="finding-<?= e($key) ?>" name="<?= e($key) ?>"<?= $key==='q' ? ' maxlength="100"' : ' type="number" min="1"' ?> value="<?= e($filterValues[$key]) ?>"></div><?php endforeach; ?>
<?php foreach (['estado'=>finding_states(),'severidad'=>finding_severities(),'orden'=>['id'=>'Más antiguos','-id'=>'Más recientes','numero'=>'Número ascendente','-numero'=>'Número descendente']] as $key=>$options): ?><div class="form-field"><label for="finding-<?= e($key) ?>"><?= e(ucfirst($key)) ?></label><select id="finding-<?= e($key) ?>" name="<?= e($key) ?>"><option value="">Todos</option><?php foreach ($options as $value=>$label): ?><option value="<?= e($value) ?>"<?= $filterValues[$key]===$value ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><?php endforeach; ?>
<div class="filter-actions"><button class="button button-secondary" type="submit">Aplicar filtros</button><a class="text-link" href="<?= e(page_url('hallazgos')) ?>">Limpiar filtros</a></div></form>
<div class="panel-heading"><h2>Hallazgos registrados</h2><span class="record-count"><?= e($findingCount) ?> registros · Página <?= e($pageNumber) ?> de <?= e($pageCount) ?></span></div>
<?php require __DIR__.'/hallazgos_list.php'; ?>
<nav class="audit-pagination" aria-label="Paginación de hallazgos"><?php if ($pageNumber>1): ?><a class="button button-secondary" href="<?= e(page_url('hallazgos',array_filter($filterValues)+['p'=>$pageNumber-1])) ?>">Anterior</a><?php endif; ?><?php if ($pageNumber<$pageCount && $pageNumber<501): ?><a class="button button-secondary" href="<?= e(page_url('hallazgos',array_filter($filterValues)+['p'=>$pageNumber+1])) ?>">Siguiente</a><?php endif; ?></nav></section>
